//Level code generated by custom Ablaze level exporter!

package Levels
{
	import org.flixel.*;
	public class Forest3Level extends BaseLevel
	{
		//Embedded media...
		[Embed(source="../../csv/levelCSV_Forest3_Map_Background.csv", mimeType="application/octet-stream")] public var CSV_MapBackground:Class;
		[Embed(source="../../assets/art/background.png")] public var Img_MapBackground:Class;
		[Embed(source="../../csv/levelCSV_Forest3_Map_Platforms.csv", mimeType="application/octet-stream")] public var CSV_MapPlatforms:Class;
		[Embed(source="../../assets/art/tiles.png")] public var Img_MapPlatforms:Class;

		//Tilemaps
		public var layerMapBackground:FlxTilemap;
		public var layerMapPlatforms:FlxTilemap;

		//Sprites
		public var ActorsPlayerGroup:FlxGroup = new FlxGroup;


		public function Forest3Level(addToStage:Boolean = true, onAddSpritesCallback:Function = null)
		{
			// Generate maps.
			layerMapBackground = new FlxTilemap;
			layerMapBackground.loadMap( new CSV_MapBackground, Img_MapBackground, 192,336, FlxTilemap.OFF, 0, 1, 1 );
			layerMapBackground.x = 0.000000;
			layerMapBackground.y = 0.000000;
			layerMapBackground.scrollFactor.x = 0.700000;
			layerMapBackground.scrollFactor.y = 1.000000;
			layerMapPlatforms = new FlxTilemap;
			layerMapPlatforms.loadMap( new CSV_MapPlatforms, Img_MapPlatforms, 16,16, FlxTilemap.OFF, 0, 1, 1 );
			layerMapPlatforms.x = 0.000000;
			layerMapPlatforms.y = 0.000000;
			layerMapPlatforms.scrollFactor.x = 1.000000;
			layerMapPlatforms.scrollFactor.y = 1.000000;

			//Add layers to the master group in correct order.
			masterLayer.add(layerMapBackground);
			masterLayer.add(layerMapPlatforms);
			masterLayer.add(ActorsPlayerGroup);


			if ( addToStage )
			{
				addSpritesForLayerActorsPlayer(onAddSpritesCallback);
				FlxG.state.add(masterLayer);
			}

			mainLayer = layerMapPlatforms;

			boundsMinX = 0;
			boundsMinY = 0;
			boundsMaxX = 768;
			boundsMaxY = 336;

		}

		public function addSpritesForLayerActorsPlayer(onAddCallback:Function = null):void
		{
			addSpriteToLayer(Player, ActorsPlayerGroup , 208.000, 128.000, 0.000, false, 1, 1, onAddCallback );//"Ember"
		}


	}
}
